version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: ecommerce-backend
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "8080:8081"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6379:6379"

  frontend:
    image: ecommerce-frontend
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
